Added first draft of database query syntax
viabzalov/graph-database pull request #11
Opened 2020-11-12 18:01 UTC by viabzalov

* Добавлен конкретный синтаксис для запросов к БД `Syntax.txt`
* Добавлен валидатор запросов `checker.py`
* В `README` добавлено описание синтаксиса, валидатора и примеры запросов

2020-11-26 07:28 UTC, gsvgit requested changes
Валидатор --- это здорово. Но нужны и автоматические тесты, проверяющие, что граммтика хоть как-то соответствует ожиданиям (можно разбирать ожидаемые конструкции).

2020-11-26 09:10 UTC, viabzalov commented
Я считаю, что приведенного синтаксиса и примеров работающих скриптов достаточно для того, чтобы понять, что грамматика соответствует ожиданиям.

2020-11-26 10:24 UTC, gsvgit commented
Это да. Проблема в том, тчо жто автоматически не проверяется.

Вот поменяем CYK, всё развалится, никто не заметит. Ровно для того и нужны
тесты.

Regards,
Semyon Grigorev.


чт, 26 нояб. 2020 г. в 12:10, Vadim Abzalov <notifications@github.com>:

> @viabzalov <https://github.com/viabzalov> requested your review on: #11
> <https://github.com/viabzalov/graph-database/pull/11> Added first draft
> of database query syntax.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/viabzalov/graph-database/pull/11#event-4041515869>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQH55MJBKCU5LHEZ37LSRYLR5ANCNFSM4TTTKBZQ>
> .
>

2020-11-27 09:18 UTC, viabzalov commented
* Добавлены тесты

2020-11-30 09:24 UTC, gsvgit approved these changes
Ок.

2020-11-30 09:26 UTC, merged